services:
  totvs.ats.webapi:
    image: totvs.ats.webapi
    build:
      context: .
      dockerfile: Totvs.ATS.WebAPI/Dockerfile

  webapplication1:
    image: webapplication1
    build:
      context: .
      dockerfile: WebApplication1/Dockerfile

  totvs.ats.webapi-1:
    image: totvs.ats.webapi-1
    build:
      context: .
      dockerfile: Totvs.ATS.WebAPI/Dockerfile

  totvs.ats.webapi-2:
    image: totvs.ats.webapi-2
    build:
      context: .
      dockerfile: Totvs.ATS.WebAPI/Dockerfile

